server:
  port: 8085
  
spring:
  application:
      name: CONFIG-SERVER
   
  #it will read data from git hub
  cloud:
   config:
    server:
        git:
         uri: https://github.com/Raghvendra35/microservice_config_server
         clone-on-start: true